<a href="https://colab.research.google.com/github/yawarabbasmalik/NLP-Text-Analysis-on-Yelp-Dataset/blob/main/NLP_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
import pandas as pd

# Read the dataset and extract the 'Review' column
df = pd.read_csv('Yelp Dataset2.csv')

<ipython-input-1-6f301df0a8fc>:5: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Yelp Dataset2.csv')

In [ ]:
df.head()

,User_id,Product_id,Rating,Date,Review,Label
0,923.0,0.0,3.0,12/8/2014,The food at snack is a selection of popular Gr...,-1.0
1,924.0,0.0,3.0,5/16/2013,This little place in Soho is wonderful. I had ...,-1.0
2,925.0,0.0,4.0,7/1/2013,ordered lunch for 15 from Snack last Friday. Â...,-1.0
3,926.0,0.0,4.0,7/28/2011,This is a beautiful quaint little restaurant o...,-1.0
4,927.0,0.0,4.0,11/1/2010,Snack is great place for a Â casual sit down l...,-1.0

In [ ]:
# Create a new DataFrame with 'Review' and 'Label' columns
df = df[['Review', 'Label']]

# Drop all other columns
df = df.drop(columns=[col for col in df.columns if col not in ['Review', 'Label']])

In [ ]:
df.head()

                                              Review  Label
0  The food at snack is a selection of popular Gr...   -1.0
1  This little place in Soho is wonderful. I had ...   -1.0
2  ordered lunch for 15 from Snack last Friday. Â...   -1.0
3  This is a beautiful quaint little restaurant o...   -1.0
4  Snack is great place for a Â casual sit down l...   -1.0

**Word Tokenization**

This code snippet applies tokenization on the "Review" column of the DataFrame df. The apply() method is used to iterate over each element in the "Review" column. The lambda function lambda x: word_tokenize(str(x)) is applied to each element, ensuring that the values are converted to strings using str() before tokenization.

In [ ]:
nltk.download('punkt')

from nltk.tokenize import word_tokenize


# Convert values in 'Review' column to string type
df['Review'] = df['Review'].astype(str)

# Apply tokenization on the 'Review' column
df['Tokenized_Review'] = df['Review'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
print (df['Tokenized_Review'])

0         [The, food, at, snack, is, a, selection, of, p...
1         [This, little, place, in, Soho, is, wonderful,...
2         [ordered, lunch, for, 15, from, Snack, last, F...
3         [This, is, a, beautiful, quaint, little, resta...
4         [Snack, is, great, place, for, a, Â, casual, s...
                                ...
359047                                                [nan]
359048                                                [nan]
359049                                                [nan]
359050                                                [nan]
359051                                                [nan]
Name: Tokenized_Review, Length: 359052, dtype: object

In [ ]:
df.head()

,Review,Label,Tokenized_Review
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s..."

**Stop Words**

In this updated code, we first import the necessary libraries, including nltk and stopwords. We download the required resources using nltk.download() for both tokenization and stop words.

After tokenizing the reviews using word_tokenize(), we assign the tokenized results to the new column 'Tokenized_Review' in the DataFrame df.

Next, we proceed with stop words removal. We create a set of English stop words using stopwords.words('english'). Then, we apply a lambda function using apply() on the 'Tokenized_Review' column. The lambda function iterates over each review, removing any stop words using a list comprehension, and assigns the filtered results to the new column 'Filtered_Review' in the DataFrame df.

By incorporating these modifications, the code should now execute correctly, performing both tokenization and stop words removal on the 'Review' column of the DataFrame df.

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

# Stop words removal
stop_words = set(stopwords.words('english'))
df['Filtered_Review'] = df['Tokenized_Review'].apply(lambda x: [word for word in x if word.lower() not in stop_words])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ..."

**Lemmatization**

In this updated code, we first import the necessary libraries, including nltk, stopwords, and WordNetLemmatizer. We download the required resources using nltk.download() for tokenization, stopwords, and WordNet.

After tokenizing the reviews using word_tokenize(), we assign the tokenized results to the new column 'Tokenized_Review' in the DataFrame df.

Next, we proceed with stop words removal. We create a set of English stop words using stopwords.words('english'). Then, we apply a lambda function using apply() on the 'Tokenized_Review' column. The lambda function iterates over each review, removing any stop words using a list comprehension, and assigns the filtered results to the new column 'Filtered_Review' in the DataFrame df.

Finally, we perform lemmatization using the WordNetLemmatizer. We create an instance of the lemmatizer. Then, we apply a lambda function using apply() on the 'Filtered_Review' column. The lambda function iterates over each review, lemmatizing each word using the lemmatize() method, and assigns the lemmatized results to the new column 'Lemmatized_Review' in the DataFrame df.

By incorporating these modifications, the code should now correctly perform tokenization, stop words removal, and lemmatization on the 'Review' column of the DataFrame df.

In [ ]:
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

# Lemmatization
lemmatizer = WordNetLemmatizer()
df['Lemmatized_Review'] = df['Filtered_Review'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review,Lemmatized_Review
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe...","[food, snack, selection, popular, Greek, dish,..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, Soho, wonderful, ., lamb, sand..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, Snack, last, Friday, ., Â..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ...","[Snack, great, place, Â, casual, sit, lunch-, ..."

**Text Normalization**

In [ ]:
# Text normalization
df['Normalized_Review'] = df['Lemmatized_Review'].apply(lambda x: [word.lower() for word in x])

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review,Lemmatized_Review,Normalized_Review
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe...","[food, snack, selection, popular, Greek, dish,...","[food, snack, selection, popular, greek, dish,..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, snack, last, friday, ., â..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ...","[Snack, great, place, Â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ..."

**Case Normalizataion**

In this adjusted code, we added the case normalization step after text normalization.

After performing text normalization, we assigned the normalized results to the new column 'Normalized_Review' in the DataFrame df.

Next, we proceeded with case normalization by applying two separate lambda functions. The first lambda function converts each word in the normalized review to lowercase using lower(), and the results are assigned to the new column 'Normalized_Review_Lower' in the DataFrame df. The second lambda function converts each word in the normalized review to uppercase using upper(), and the results are assigned to the new column 'Normalized_Review_Upper' in the DataFrame df.

By incorporating these modifications, the code will now perform tokenization, stop words removal, lemmatization, text normalization, and case normalization on the 'Review' column of the DataFrame df.

In [ ]:
# Case normalization
df['Normalized_Review_Lower'] = df['Normalized_Review'].apply(lambda x: [word.lower() for word in x])
df['Normalized_Review_Upper'] = df['Normalized_Review'].apply(lambda x: [word.upper() for word in x])

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review,Lemmatized_Review,Normalized_Review,Normalized_Review_Lower,Normalized_Review_Upper
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe...","[food, snack, selection, popular, Greek, dish,...","[food, snack, selection, popular, greek, dish,...","[food, snack, selection, popular, greek, dish,...","[FOOD, SNACK, SELECTION, POPULAR, GREEK, DISH,..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[LITTLE, PLACE, SOHO, WONDERFUL, ., LAMB, SAND..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ORDERED, LUNCH, 15, SNACK, LAST, FRIDAY, ., Â..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[BEAUTIFUL, QUAINT, LITTLE, RESTAURANT, PRETTY..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ...","[Snack, great, place, Â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[SNACK, GREAT, PLACE, Â, CASUAL, SIT, LUNCH-, ..."

**Eliminating Null & Duplicate Values (Rows)**

In this adjusted code, we added the steps to remove null values and duplicates after the case normalization step.

After performing case normalization, we removed null values using the dropna() method. By specifying subset=['Normalized_Review_Lower'], we ensure that rows with null values in the 'Normalized_Review_Lower' column are dropped from the DataFrame df.

Next, we removed duplicates using the drop_duplicates() method. By specifying subset=['Normalized_Review_Lower'], we ensure that only rows with duplicated values in the 'Normalized_Review_Lower' column are dropped from the DataFrame df.

By incorporating these modifications, the code will now perform tokenization, stop words removal, lemmatization, text normalization, case normalization, removal of null values, and removal of duplicates on the 'Review' column of the DataFrame df.

In [ ]:
# Remove null values
df = df.dropna(subset=['Normalized_Review_Lower'])

# Remove duplicates
df = df.drop_duplicates(subset=['Normalized_Review_Lower'])

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review,Lemmatized_Review,Normalized_Review,Normalized_Review_Lower,Normalized_Review_Upper
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe...","[food, snack, selection, popular, Greek, dish,...","[food, snack, selection, popular, greek, dish,...","[food, snack, selection, popular, greek, dish,...","[FOOD, SNACK, SELECTION, POPULAR, GREEK, DISH,..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[LITTLE, PLACE, SOHO, WONDERFUL, ., LAMB, SAND..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ORDERED, LUNCH, 15, SNACK, LAST, FRIDAY, ., Â..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[BEAUTIFUL, QUAINT, LITTLE, RESTAURANT, PRETTY..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ...","[Snack, great, place, Â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[SNACK, GREAT, PLACE, Â, CASUAL, SIT, LUNCH-, ..."

**Part-of-Speech (POS) tagging**

In this adjusted code, we added the step to perform Part-of-Speech (POS) tagging on the 'Normalized_Review_Lower' column of the DataFrame df.

After performing all the previous preprocessing steps, we apply the nltk.pos_tag function using apply() and assign the resulting POS tags to the new column 'POS_Tags' in the DataFrame df.

By incorporating these modifications, the code will now perform tokenization, stop words removal, lemmatization, text normalization, case normalization, removal of null values, removal of duplicates, and Part-of-Speech tagging on the 'Review' column of the DataFrame df.

In [ ]:
nltk.download('averaged_perceptron_tagger')

# Part-of-Speech tagging
df['POS_Tags'] = df['Normalized_Review_Lower'].apply(nltk.pos_tag)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [ ]:
df.head()

,Review,Label,Tokenized_Review,Filtered_Review,Lemmatized_Review,Normalized_Review,Normalized_Review_Lower,Normalized_Review_Upper,POS_Tags
0,The food at snack is a selection of popular Gr...,-1.0,"[The, food, at, snack, is, a, selection, of, p...","[food, snack, selection, popular, Greek, dishe...","[food, snack, selection, popular, Greek, dish,...","[food, snack, selection, popular, greek, dish,...","[food, snack, selection, popular, greek, dish,...","[FOOD, SNACK, SELECTION, POPULAR, GREEK, DISH,...","[(food, NN), (snack, NN), (selection, NN), (po..."
1,This little place in Soho is wonderful. I had ...,-1.0,"[This, little, place, in, Soho, is, wonderful,...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, Soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[little, place, soho, wonderful, ., lamb, sand...","[LITTLE, PLACE, SOHO, WONDERFUL, ., LAMB, SAND...","[(little, JJ), (place, NN), (soho, NN), (wonde..."
2,ordered lunch for 15 from Snack last Friday. Â...,-1.0,"[ordered, lunch, for, 15, from, Snack, last, F...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, Snack, last, Friday, ., Â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ordered, lunch, 15, snack, last, friday, ., â...","[ORDERED, LUNCH, 15, SNACK, LAST, FRIDAY, ., Â...","[(ordered, VBN), (lunch, NN), (15, CD), (snack..."
3,This is a beautiful quaint little restaurant o...,-1.0,"[This, is, a, beautiful, quaint, little, resta...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[beautiful, quaint, little, restaurant, pretty...","[BEAUTIFUL, QUAINT, LITTLE, RESTAURANT, PRETTY...","[(beautiful, JJ), (quaint, NN), (little, JJ), ..."
4,Snack is great place for a Â casual sit down l...,-1.0,"[Snack, is, great, place, for, a, Â, casual, s...","[Snack, great, place, Â, casual, sit, lunch-, ...","[Snack, great, place, Â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[snack, great, place, â, casual, sit, lunch-, ...","[SNACK, GREAT, PLACE, Â, CASUAL, SIT, LUNCH-, ...","[(snack, RB), (great, JJ), (place, NN), (â, NN..."

In [ ]:
# Save the final DataFrame to a CSV file
df.to_csv('preprocessed_data.csv', index=False)